name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  firebase_app_check: ^0.3.2+5
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  
  # Routing
  go_router: ^15.0.0
  
  # UI Components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_markdown: ^0.6.22
  lottie: ^3.2.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  
  # Utils
  intl: 0.20.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  logger: ^2.0.2+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.7
  google_generative_ai: ^0.4.2
  
  # OCR ve Görüntü İşleme
  path_provider: ^2.1.5
  path: ^1.8.3
  google_mlkit_text_recognition: ^0.14.0
  
  # iOS ve macOS için ek destekler
  permission_handler: ^11.2.0
  file_selector: ^1.0.3
  percent_indicator: ^4.2.5
  image: ^4.1.7
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/logo.jpg
  android_12:
    color: "#FFFFFF"
    image: assets/icons/logo.jpg
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#6750A4"
  adaptive_icon_foreground: "assets/icons/logo.jpg"
