// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mpCgEDmU5L9BxnhLnBOFrfBvKqw_Mn4',
    appId: '1:768992590332:web:your_web_app_id',
    messagingSenderId: '768992590332',
    projectId: 'flortya-7db8c',
    authDomain: 'flortya-7db8c.firebaseapp.com',
    storageBucket: 'flortya-7db8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0mpCgEDmU5L9BxnhLnBOFrfBvKqw_Mn4',
    appId: '1:768992590332:android:8182ea174bdfd514575a79',
    messagingSenderId: '768992590332',
    projectId: 'flortya-7db8c',
    storageBucket: 'flortya-7db8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39eBYirwuO7Vzd6N6KCoPwS-9pQzCfoo',
    appId: '1:768992590332:ios:de3847845fd03f52575a79',
    messagingSenderId: '768992590332',
    projectId: 'flortya-7db8c',
    storageBucket: 'flortya-7db8c.firebasestorage.app',
    iosBundleId: 'com.rivorya.flortya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39eBYirwuO7Vzd6N6KCoPwS-9pQzCfoo',
    appId: '1:768992590332:ios:de3847845fd03f52575a79',
    messagingSenderId: '768992590332',
    projectId: 'flortya-7db8c',
    storageBucket: 'flortya-7db8c.firebasestorage.app',
    iosBundleId: 'com.rivorya.flortya',
  );
} 